name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Check if build was successful
      run: |
        if [ $? -eq 0 ]; then
          echo "Build successful. Deploying to deploy branch."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b deploy
          git add .
          git commit -m "Deploy latest build"
          git push --set-upstream origin deploy
        else
          echo "Build failed. Check the build logs for more information."
          exit 1
        fi
